language: java

before_install:
  - mysql -e 'CREATE DATABASE crowdguru' -u root
  - echo "GRANT ALL ON crowdguru.* TO 'crowdguru'@'localhost' IDENTIFIED BY 'crowdguru';" | mysql -u root

install: mvn install -DskipTests=true -Dcobertura.skip=true

script: mvn test

after_failure: 
  - cat webapp/target/cargo/configurations/jetty7x/logs/*.log
  - cat webapp/target/failsafe-reports/*.txt

after_success: mvn verify

after_script: mvn cobertura:cobertura

